### PR TITLE
Fix issue #110 - Convert cbp-theme custom JS from IIFE to modules

### PR DESCRIPTION
**Pull request by d-amit**
Updated all cbp-theme js helper files from IIFE to modules.  Only updated webpack config to include the helpers (minus inputmask).  I didn't want to change the implementation for inputmask for now. I suspect when someone updates it to use the latest inputmask dependencies, they can update implementation then.  

Please review and make changes as needed.

### CODE REVIEW

**Comment by djKianoosh** [comment]
It's high time we ditch webpack and go to rollup

**Comment by d-amit** [comment]
@davezen1 and/or @mkayan - please take review this request

**Comment by davezen1** [comment]
It looks like we also need to fix the eslinting.  Can you fix that as part of this PR? The kitchensink.js should also be part of the linting.

**Comment by d-amit** [comment]
@davezen1 - please create another issue for the issue as that's a separate issue.  I was hoping that this one get resolved soon since we have a apps that are looking to us CBP-theme.

**Comment by davezen1** [comment]
I created #136 to fix linting.  I'll get it done this week. Then you can either make sure the new code makes it thru the linter...or I can do it.  Ideally we would have tests as well...there is an issue for that too that I should get too in the next few weeks.

**Comment by davezen1** [comment]
Just submitted a PR for linting, and we have a few minor PRs to resolve.  I'll take another look at these changes. For a workaround, you could use your js instead of the cbp-theme.js.

**Comment by davezen1** [comment]
@d-amit were you able to find a workaround? I'd like to close this or have you do an update to this PR.

**Comment by davezen1** [comment]
@yogeshgadge this may be related to moving toward a different build to produce different artifacts such as Typescript.

**Comment by davezen1** [comment]
Closing this PR as we will be udpating the build process which will address this request.

**Pull request closed without merging**
