### PR TITLE
Badge Colors fix

### PR DESCRIPTION
**Pull request by millerbennett**
Fixing issue where badge colors, ex: badge-warning, badge-danger, or badge-success would not be orange, red, or green, but blue. Increased specificity of the modifier classes.

badge_colors_fix_2

### CODE REVIEW

**Comment by davezen1** [comment]
@millerbennett not sure we want to error success warning badges. In general we look to badges for an emphasis on a single number, like unread emails. You may consider this:

Label 1 + badge
Label 2 + badge

I will let some other folks chime in: @HMcFabulous @tma001

**Comment by millerbennett** [comment]
We have a use case where we display the number of errors on a page. I do
realize it might be a rate use case.  The classes were already there anyway?

**Comment by cmterrylynn** [comment]
508 wise, the color of the badge cannot convey meaning without another form of on screen meaning as well. Think color blind. They won't see any alt text provided, and won't be able to distinguish the color. We recommend the alpha of either the color or its meaning inside the badge. Could be alongside the number count.

________________________________
From: Bennett Miller
Sent: Thursday, November 10, 2016 4:49:56 PM
To: US-CBP/cbp-theme
Subject: [US-CBP/cbp-theme] Badge Colors fix (#60)


Fixing issue where badge colors, ex: badge-warning, badge-danger, or badge-success would not be orange, red, or green, but blue. Increased specificity of the modifier classes.

[badge_colors_fix]<https://cloud.githubusercontent.com/assets/2319831/20195698/94ecd770-a765-11e6-986f-846ba3ea2f80.png>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/US-CBP/cbp-theme/pull/60

Commit Summary

  *   Fixing issue where badge colors, ex: badge-warning, badge-danger, or badge-success would not be orange, red, or green, but blue. Increased specificity of the modifier classes.

File Changes

  *   M app/kitchensink/dist/cbp-theme.css<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-0> (11063)
  *   M app/kitchensink/dist/cbp-theme.js<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-1> (56)
  *   A app/kitchensink/dist/cbp-theme.min.js<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-2> (4)
  *   M app/kitchensink/dist/fontawesome-webfont.eot<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-3> (0)
  *   M app/kitchensink/dist/fontawesome-webfont.svg<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-4> (3350)
  *   M app/kitchensink/dist/fontawesome-webfont.ttf<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-5> (0)
  *   M app/kitchensink/dist/fontawesome-webfont.woff<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-6> (0)
  *   M app/kitchensink/dist/fontawesome-webfont.woff2<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-7> (0)
  *   M app/kitchensink/dist/inputmask.js<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-8> (33)
  *   A app/kitchensink/dist/inputmask.min.js<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-9> (4)
  *   M app/kitchensink/dist/jquery.js<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-10> (14)
  *   A app/kitchensink/dist/jquery.min.js<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-11> (1)
  *   M app/kitchensink/index.html<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-12> (8)
  *   M app/styles/custom/scss/_badges.scss<https://github.com/US-CBP/cbp-theme/pull/60/files#diff-13> (31)

Patch Links:

  *   https://github.com/US-CBP/cbp-theme/pull/60.patch
  *   https://github.com/US-CBP/cbp-theme/pull/60.diff

**Comment by millerbennett** [comment]
I see, yes, I agree. We certainly shouldn't be relying solely on the color to convey meaning. In our case, we also provide text conveying the meaning of the number via a tooltip as well as an aria-label. The example in the kitchen sink I created definitely does not represent a good usage though. What I can do is update the example to include a label next to the number (as well as maybe a short comment explaining why it needs a label).

Having the option to use color to provide a "shortcut" to the meaning is a good idea and should be supported (the same concept applies to alerts, toasts, buttons.. etc.).

One quick example: let's say you are displaying the results of a batch job in a table in which 98 jobs passed and 2 jobs failed. Apart from the column headers that describe the numbers, would it not also be nice to highlight the number passed in green and the number failed in red? For ~92% of users, I think it made the results easier to understand.

**Comment by cmterrylynn** [comment]
My main concern with the color and badges is where say the color indicates green - fully cleared, yellow-suspicious, red-hold.   If the number in the color badge indicates the number of shipments in each status, it's not the number that is not clear, but the status that the color indicates. Make sense?

________________________________

**Comment by millerbennett** [comment]
Right, I thought I made that clear, the developer cannot rely on the color to indicate the status. That does not mean that color _can't_ be a useful tool in conveying meaning.

I would also just like to throw it out there.. the work had already been done in the framework so someone else working on the CAF team must have thought it was a good idea too. Look at the diff. I just fixed it so that the class definitions would not get overridden.

**Comment by millerbennett** [comment]
Check out the new example.

**Comment by cmterrylynn** [comment]
Looks good.  The only thing now is to be sure you have table mark up so the data is related to the columns it falls in.  Make sense?

**Comment by millerbennett** [comment]
Updated to associate cells with their respective headers via the scope attribute.

**Comment by cmterrylynn** [comment]
Thanks, Miller!

**Comment by millerbennett** [comment]
Sure thing. First name is Bennett :)

**Comment by davezen1** [comment]
@millerbennett I think the example is fine and could be even showcased for other projects who are doing something similar.  I don't think it belongs in the examples, yet.  While we love the contributions it can difficult to accept the multitude of examples, yet.  I think we should keep this open and when we fix all of our current issues we can revisit.

**Comment by millerbennett** [comment]
I have removed the example. The kitchen sink is kind of.. long as it is and I can see why keeping it simple is desired.

**Comment by davezen1** [comment]
@millerbennett feel free to discuss on our Slack channel.  We plan to move the Kitchen Sink out of the theme's repository and treat as a standalone starter app.

**Comment by cmterrylynn** [comment]
Do we want a fresh pass through for 508 before it moves?

**Comment by millerbennett** [comment]
Hey guys, Seacats wants to use the CBP Theme. The badge colors is one of several things that we want to update.. we don't want to have to do a bunch of local overrides. Could we get this merged in, please?

**Comment by davezen1** [comment]
@millerbennett done and published to npm as version 1.0.1

**Pull request merged**
