### PR TITLE
Remove webpack specific ~, folder structure refactoring, introduced roboto-fontface 

### PR DESCRIPTION
**Pull request by yogeshgadge**
Removed ~ so that the module is resolved by looking up from `node_modules` as suggested by @djKianoosh 
   This allows all teams to 
Folder structure changes
     Reduced `styles/custom/scss` to `styles/custom`
     Moved `main.scss` out of custom for simplicity
Build was breaking due to roboto.css urls due to sassLoader webpack config
     Removed roboto.css
     Introduced npm module `roboto-fontface` and used its scss files.

### CODE REVIEW

**Comment by djKianoosh** [comment]
Since you were working on a master branch in your fork, I pushed this to my fork under a different branch: https://github.com/djKianoosh/cbp-theme/tree/pr-97

I'll take a look and try it out with one of my new test projects to see if there are any further changes.

**Comment by davezen1** [comment]
@yogeshgadge It would be good to only distribute the Roboto fonts that we mentioned in the CBP Style Guide and what we originally downloaded with the package.json script.  We could update the _roboto.scss file to pull in the individual fonts and not the whole roboto family like so:

`roboto-fontface-light-italic.scss 
`
screen shot 2017-07-21 at 4 11 12 pm

**Comment by yogeshgadge** [comment]
Done

**Comment by davezen1** [comment]
Looks good thanks.

**Pull request merged**
