### PR TITLE
Fixes issues 192

### PR DESCRIPTION
**Pull request by jfinest**
#### What's this PR do?
Upgraded from jQuery 2.2.4 to 3.3.1

#### How should this be manually tested?

With the console open, test the different components in the kitchen sink.

#### What are the relevant tickets?

192

#### Screenshots (if appropriate)
N/A
#### Questions:
- Is there a blog post?
No

- Does the knowledge base need an update?

### CODE REVIEW

**Comment by r1teshkumar** [comment]
We will hold off on merging this PR till https://github.com/US-CBP/cbp-theme/pull/206 is merged

**Comment by r1teshkumar** [comment]
@davezen1, developer documentation should be part of the Release Notes.

**Comment by r1teshkumar** [comment]
@jfinest , looks like there are conflicts that need to be resolved.

**Comment by jfinest** [comment]
Resolved conflicts

**Pull request merged**
